CREATE TABLE IF NOT EXISTS roles (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	date_of_birth DATE NOT NULL,
	gender TINYINT NOT NULL COMMENT'0=male,1=female,2=other',
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	role_id INT NOT NULL,
	enabled BOOLEAN NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at DATETIME NULL,
	FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE IF NOT EXISTS qualifications (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	estimated_minutes INT NOT NULL,
	created_by_user_id INT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS goals (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL COMMENT'minutes',
	qualification_id INT NOT NULL,
	start_date DATETIME NOT NULL,
	goal_date DATETIME NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	ended_at DATETIME NULL,
	FOREIGN KEY (user_id) REFERENCES users (id),
	FOREIGN KEY (qualification_id) REFERENCES qualifications (id)
);

CREATE TABLE IF NOT EXISTS learning_records (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	goal_id INT NOT NULL,
	learning_day DATE NOT NULL,
	start_time TIME NULL,
	end_time TIME NULL,
	learning_minutes INT NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users (id),
	FOREIGN KEY (goal_id) REFERENCES goals (id)
);

CREATE TABLE IF NOT EXISTS routine_schedules (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT NOT NULL,
	title VARCHAR(100) NOT NULL,
	start_time TIME NOT NULL,
	end_time TIME NOT NULL,
	effective_from DATE NOT NULL,
	effective_to DATE DEFAULT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS routine_schedule_days (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	routine_schedule_id BIGINT NOT NULL,
	day_of_week VARCHAR(10) NOT NULL,
	CONSTRAINT fk_routine_schedule
	FOREIGN KEY (routine_schedule_id) REFERENCES routine_schedules (id)
	ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS learning_plans (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	goal_id INT NOT NULL,
	planning_day DATE NOT NULL,
	start_time TIME NULL,
	end_time TIME NULL,
	planning_minutes INT NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users (id),
	FOREIGN KEY (goal_id) REFERENCES goals (id)
);	