CREATE TABLE IF NOT EXISTS roles (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	date_of_birth DATE NOT NULL,
	gender SMALLINT NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	role_id INTEGER NOT NULL,
	enabled BOOLEAN NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL,
	CONSTRAINT fk_users_roles FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE IF NOT EXISTS qualifications (
	id SERIAL PRIMARY KEY,
	root_qualification_id INTEGER NOT NULL,
	name VARCHAR(255) NOT NULL,
	estimated_minutes INTEGER NOT NULL,
	created_by_user_id INTEGER NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS goals (
	id SERIAL PRIMARY KEY,
	user_id BIGINT NOT NULL,
	qualification_id INTEGER NOT NULL,
	start_date TIMESTAMP NOT NULL,
	goal_date TIMESTAMP NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ended_at TIMESTAMP NULL,
	CONSTRAINT fk_goals_user FOREIGN KEY (user_id) REFERENCES users (id),
	CONSTRAINT fk_goals_qualification FOREIGN KEY (qualification_id) REFERENCES qualifications (id)
);

CREATE TABLE IF NOT EXISTS learning_records (
	id SERIAL PRIMARY KEY,
	user_id BIGINT NOT NULL,
	goal_id INTEGER NOT NULL,
	learning_day DATE NOT NULL,
	start_time TIME NULL,
	end_time TIME NULL,
	learning_minutes INTEGER NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_lr_user FOREIGN KEY (user_id) REFERENCES users (id),
	CONSTRAINT fk_lr_goal FOREIGN KEY (goal_id) REFERENCES goals (id)
);

CREATE TABLE IF NOT EXISTS routine_schedules (
	id BIGSERIAL PRIMARY KEY,
	user_id BIGINT NOT NULL,
	title VARCHAR(100) NOT NULL,
	start_time TIME NOT NULL,
	end_time TIME NOT NULL,
	effective_from DATE NOT NULL,
	effective_to DATE NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS routine_schedule_days (
	id BIGSERIAL PRIMARY KEY,
	routine_schedule_id BIGINT NOT NULL,
	day_of_week VARCHAR(10) NOT NULL,
	CONSTRAINT fk_rsd_schedule
	FOREIGN KEY (routine_schedule_id) REFERENCES routine_schedules (id)
	ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS learning_plans (
	id SERIAL PRIMARY KEY,
	user_id BIGINT NOT NULL,
	goal_id INTEGER NOT NULL,
	planning_day DATE NOT NULL,
	start_time TIME NULL,
	end_time TIME NULL,
	planning_minutes INTEGER NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_lp_user FOREIGN KEY (user_id) REFERENCES users (id),
	CONSTRAINT fk_lp_goal FOREIGN KEY (goal_id) REFERENCES goals (id)
);	